

#
# Host specific setup file
# Common to bash and zsh
#

#NOSLACfunction _CommonSLACSettings
#NOSLAC        {
#NOSLAC
#NOSLAC        EPICS_VERSION="R7.0.3.1-1.0"
#NOSLAC        PYTHON_VERSION="3.7.2"
#NOSLAC
#NOSLAC        epicsDir="epics/base/${EPICS_VERSION}"
#NOSLAC
#NOSLAC        #
#NOSLAC        # if AFS and /usr/local both exist,
#NOSLAC        # get EPICS from /usr/local.
#NOSLAC        #
#NOSLAC        if [[ -d "/usr/local/lcls/${epicsDir}" ]];
#NOSLAC        then
#NOSLAC                export EPICS_BASE=${EPICS_BASE:-"/usr/local/lcls/${epicsDir}"}
#NOSLAC        fi
#NOSLAC
#NOSLAC        if [[ -d "/afs/slac/g/lcls/${epicsDir}" ]];
#NOSLAC        then
#NOSLAC                export EPICS_BASE=${EPICS_BASE:-"/afs/slac/g/lcls/${epicsDir}"}
#NOSLAC        fi
#NOSLAC        unset epicsDir
#NOSLAC
#NOSLAC        #
#NOSLAC        # find the host architecture
#NOSLAC        #
#NOSLAC        if [[ -r ${EPICS_BASE}/startup/EpicsHostArch ]];
#NOSLAC        then
#NOSLAC                export EPICS_HOST_ARCH=$(${EPICS_BASE}/startup/EpicsHostArch)
#NOSLAC        fi
#NOSLAC 
#NOSLAC        #
#NOSLAC        # set up other local variables relating to
#NOSLAC        # modules, extensions and the facility
#NOSLAC        #
#NOSLAC        EPICS_SETUP="${EPICS_BASE}/../../setup"
#NOSLAC        if [[ -r ${EPICS_SETUP}/epicsenv-${EPICS_VERSION}.bash ]];
#NOSLAC        then
#NOSLAC                source ${EPICS_SETUP}/epicsenv-${EPICS_VERSION}.bash
#NOSLAC        fi
#NOSLAC
#NOSLAC        #
#NOSLAC        # assume Rocky9 if HOST not set
#NOSLAC        #
#NOSLAC        export EPICS_HOST_ARCH=${EPICS_HOST_ARCH:-"rhel9-x86_64"}
#NOSLAC
#NOSLAC        if ! type newlist &>/dev/null
#NOSLAC        then
#NOSLAC                printf "The newlist function is not available.  Functionality will be limited."
#NOSLAC                return
#NOSLAC        fi
#NOSLAC
#NOSLAC        #
#NOSLAC        # At this point, we know
#NOSLAC        # path support is available
#NOSLAC        #
#NOSLAC        addpath -q ${EPICS_BASE}/bin/${EPICS_HOST_ARCH}/
#NOSLAC
#NOSLAC        #
#NOSLAC        # if AFS and /usr/local both exist,
#NOSLAC        # get Python from /usr/local.
#NOSLAC        #
#NOSLAC        if [[ -d "/usr/local/lcls/package" ]];
#NOSLAC        then
#NOSLAC                export PACKAGE_TOP=${PACKAGE_TOP-"/usr/local/lcls/package"}
#NOSLAC                inspath -q $PACKAGE_TOP/anaconda/envs/python3_rhel7_env/bin
#NOSLAC                inslib -q $PACKAGE_TOP/anaconda/envs/python3_rhel7_env/lib
#NOSLAC                inslib -q $PACKAGE_TOP/anaconda/envs/python3_rhel7_env/lib/python3.7/lib-dynload
#NOSLAC        fi
#NOSLAC
#NOSLAC        if [[ -d "/afs/slac/g/lcls/package" ]];
#NOSLAC        then
#NOSLAC                export PACKAGE_TOP=${PACKAGE_TOP-"/afs/slac/g/lcls/package"}
#NOSLAC                inspath -q $PACKAGE_TOP/python/python${PYTHON_VERSION}/linux-x86_64/bin
#NOSLAC                inslib -q $PACKAGE_TOP/python/python${PYTHON_VERSION}/linux-x86_64/lib
#NOSLAC                inslib -q $PACKAGE_TOP/python/python${PYTHON_VERSION}/linux-x86_64/lib/python3.7/lib-dynload
#NOSLAC
#NOSLAC                #
#NOSLAC                # HDF5 and net tools support
#NOSLAC                #
#NOSLAC                addpath -q /afs/slac/g/lcls/package/hdf5/1.10.8/$EPICS_HOST_ARCH/bin
#NOSLAC                addpath -q /afs/slac/package/net/bin
#NOSLAC        fi
#NOSLAC
#NOSLAC        export GIT_ROOT=${GIT_ROOT-'/afs/slac/g/cd/swe/git/repos'}
#NOSLAC        }
#NOSLAC
#NOSLACK8S_CONFIGFILE=~/.config/kubernetes/config
#NOSLACfunction checkForKubernetes
#NOSLAC        {
#NOSLAC
#NOSLAC        if [[ ! -r "${K8S_CONFIGFILE}" ]];
#NOSLAC        then
#NOSLAC                return
#NOSLAC        fi
#NOSLAC
#NOSLAC        inspath '/sdf/sw/package/kubectl/1.30.3/bin'
#NOSLAC        inspath '/sdf/sw/package/kubectx/0.9.5'
#NOSLAC        module load kubectl
#NOSLAC        module load kubectx
#NOSLAC        export KUBECONFIG=${K8S_CONFIGFILE}
#NOSLAC        #
#NOSLAC        # The following text is generated by an
#NOSLAC        # online authentication app found at
#NOSLAC        # https://k8s.slac.stanford.edu/sdf-k8s01
#NOSLAC        #
#NOSLAC        kubectl config set-cluster "k8s-sandbox" --server=https://k8s.slac.stanford.edu:443/api/k8s-sandbox
#NOSLAC        kubectl config set-credentials "drm@slac.stanford.edu@k8s-sandbox"  \
#NOSLAC                --auth-provider=oidc  \
#NOSLAC                --auth-provider-arg='idp-issuer-url=https://dex.slac.stanford.edu'  \
#NOSLAC                --auth-provider-arg='client-id=vcluster--k8s-sandbox'  \
#NOSLAC                --auth-provider-arg='client-secret=OWJpJG9ePEZMXEgkSGpMVyxDcj95Zjk3cWlFJmJ2cC5uMyskVnwiKV9gdVdKXH0+bSNgaCZ7cCknLyRNPlk/bwo=' \
#NOSLAC                --auth-provider-arg='refresh-token=' \
#NOSLAC                --auth-provider-arg='id-token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjNkYjc0OWFiMzJmYmY0YTQ2MTExMGI2MDY1NTU0NDJiNjY1ZDEwMzgifQ.eyJpc3MiOiJodHRwczovL2RleC5zbGFjLnN0YW5mb3JkLmVkdSIsInN1YiI6IkNoVmtjbTFBYzJ4aFl5NXpkR0Z1Wm05eVpDNWxaSFVTQkhOaGJXdyIsImF1ZCI6InZjbHVzdGVyLS1rOHMtc2FuZGJveCIsImV4cCI6MTczMzQ1Mzk3MiwiaWF0IjoxNzMzNDI1MTcyLCJhdF9oYXNoIjoiSk81TWRYLUt2SlEzS244dVhUeGF5ZyIsImNfaGFzaCI6IjA4U29STnU1TlRqWlBOVVZvUjBWVEEiLCJlbWFpbCI6ImRybUBzbGFjLnN0YW5mb3JkLmVkdSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJuYW1lIjoiZHJtIn0.wCkAavwuQQnGd7iQtHUwf00DKc2zZoyTdkC1YeKy4Mq1wPcDanEiAJqkRAi2B2hRJ8TT_N7XggM2q9rMznq233ccjAUp65BO9cVk-mToS98SV_8GA3ZtVDe-lwvFqyuGrtauZ-Zl83uCYUbT62Egqwis_S6DPWtwkeInN9Iq1wfJpkcPmea9vDESwKODMG1X1D2wnK6IxHC2RQGoG0wruPdHiQivYO0ZdN1c5ZlpLnnVsPahDzVTSYe64DsIT-phYKWd9QzLBYOeg82HHuWfD4iC78DNK6UQ3jeCZZGyxS1zxd0GMS4Gvz9olnZLfvN8dKS-QEsqWVIRGLaDny6biQ'
#NOSLAC        kubectl config set-context "k8s-sandbox" --cluster="k8s-sandbox" --user="drm@slac.stanford.edu@k8s-sandbox"
#NOSLAC        kubectl config use-context "k8s-sandbox"
#NOSLAC        }

function hostSpecificSetup
        {

        #
        # Some DHCP servers like to assign dynamic
        # and cryptic names to override the assigned
        # local hostname.  If this is a "personal"
        # computer, indicated by the  existence of a
        # specific file, then just use the initial
        # name as supplied by the computer.
        #
        if [[ "$SYS_SPECIFIC" == "MacOS" ]];
        then
                SYSTEM_NAME=$(scutil --get ComputerName)
        else
                SYSTEM_NAME=$(hostname -s)
        fi

        if type shopt &>/dev/null
        then
                shopt -s extglob
        fi

        case "$SYSTEM_NAME" in
                "MurrayMacBookPro" | "DougM3" )
                        #
                        # Personal Laptop
                        #
                        if ! type newlist &>/dev/null
                        then
                                return
                        fi

                        #
                        # conda and related
                        #
                        addpath /opt/miniforge3/bin
                        addlib /opt/miniforge3/lib

                        #
                        # wasm
                        #
                        addpath /opt/emsdk
                        addpath /opt/emsdk/upstream/emscripten
                        addpath /opt/Qt/6.10.0/wasm_singlethread/bin

                        #
                        # homebrew
                        #
                        inspath -q /opt/homebrew/bin
                        inspath -q /opt/homebrew/opt/make/libexec/gnubin
                        inspath -q /Users/dougm/Home/bin
                        inspath -q /Users/dougm/bin

                        #
                        # Support for Wine, Qt, Xcode, etc.
                        #
                        addpath -q /opt/usr/bin
                        addpath -q /opt/Qt/6.10.0/macos/bin
                        addpath -q /opt/X11/bin

                        addmaclib -q ~/Dropbox/src/lib
                        addman -q /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man

                        export XDG_CONFIG_HOME=~/.config
                        export EMSDK=/opt/emsdk

                        #
                        # check for local EPICS
                        #
                        export EPICS_BASE=${EPICS_BASE:-"/usr/local/epics/base"}
                        if [[ -d "${EPICS_BASE}" ]];
                        then
                                EPICS_SETUP=${EPICS_BASE}/config/epicsSetup.bash
                                if [[ -e $EPICS_SETUP ]];
                                then
                                        source $EPICS_SETUP
                                else
                                        export EPICS_HOST_ARCH=${EPICS_HOST_ARCH:-"darwin-x86"}
                                        addpath -q ${EPICS_BASE}/bin/${EPICS_HOST_ARCH}/
                                fi
                        fi

                        #
                        # Support for OpenDDS
                        #
                        if [[ -d ~/Dropbox/OpenDDS ]];
                        then
                                export DANCE_ROOT=unused
                                export CIAO_ROOT=unused
                                export DDS_ROOT=~/Dropbox/OpenDDS/OpenDDS-3.12
                                export ACE_ROOT=~/Dropbox/OpenDDS/OpenDDS-3.12/ACE_wrappers
                                export TAO_ROOT=~/Dropbox/OpenDDS/OpenDDS-3.12/ACE_wrappers/TAO
                                export MPC_ROOT=~/Dropbox/OpenDDS/OpenDDS-3.12/ACE_wrappers/MPC
                                addmaclib -q ${DDS_ROOT}/lib
                                addpath -q ${DDS_ROOT}/bin
                                addmaclib -q ${ACE_ROOT}/lib
                                addpath -q ${ACE_ROOT}/bin
                        fi

                        #
                        # Support for RTI DDS
                        #
                        if [[ -d /Applications/rti_connext_dds-5.3.1 ]];
                        then
                                export NDDSHOME=/Applications/rti_connext_dds-5.3.1
                                addpath -q ${NDDSHOME}/bin
                                addlib -q ${NDDSHOME}/lib/x64Darwin17clang9.0/
                                addmaclib -q ${NDDSHOME}/lib/x64Darwin17clang9.0/
                        fi

                        ;;
#NOSLAC                "PC102884" )
#NOSLAC                        #
#NOSLAC                        # SLAC MacBook Pro M2 2023
#NOSLAC                        #
#NOSLAC                        export EPICS_BASE=/usr/local/epics/epics-base
#NOSLAC                        export EPICS_HOST_ARCH=$(${EPICS_BASE}/startup/EpicsHostArch)
#NOSLAC                        inspath -q "${EPICS_BASE}/bin/${EPICS_HOST_ARCH}"
#NOSLAC                        inspath -q /opt/homebrew/bin
#NOSLAC
#NOSLAC                        export EPICS_PVA_AUTO_ADDR_LIST=YES
#NOSLAC                        addca lcls-daemon0
#NOSLAC                        addca lcls-prod01:5068
#NOSLAC                        addca lcls-prod01:5063
#NOSLAC                        ;;
#NOSLAC                "pc99383" )
#NOSLAC                        #
#NOSLAC                        # Dell Desktop Machine Rocky Linux 9
#NOSLAC                        #
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        export EPICS_BASE=/usr/local/epics/base
#NOSLAC                        if [[ -f ${EPICS_BASE}/startup/EpicsHostArch ]];
#NOSLAC                        then
#NOSLAC                                export EPICS_HOST_ARCH=$(${EPICS_BASE}/startup/EpicsHostArch)
#NOSLAC                        fi
#NOSLAC                        export EPICS_PVA_AUTO_ADDR_LIST=NO
#NOSLAC                        inspath ${EPICS_BASE}/bin/${EPICS_HOST_ARCH}
#NOSLAC                        inslib ${EPICS_BASE}/lib/${EPICS_HOST_ARCH}
#NOSLAC                        addca lcls-daemon0
#NOSLAC                        addca lcls-prod01:5068
#NOSLAC                        addca lcls-prod01:5063
#NOSLAC                        addca mcc-dmz
#NOSLAC                        ;;
#NOSLAC                "rhel6-64*" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        export EPICS_PVA_AUTO_ADDR_LIST=YES
#NOSLAC                        export EPICS_CA_AUTO_ADDR_LIST=NO
#NOSLAC                        addca lcls-daemon0
#NOSLAC                        addca lcls-prod01:5068
#NOSLAC                        addca lcls-prod01:5063
#NOSLAC                        addca mcc-dmz
#NOSLAC                        addca 134.79.219.255
#NOSLAC                        addca 172.26.97.63
#NOSLAC                        export EPICS_PVA_ADDR_LIST="$EPICS_CA_ADDR_LIST"
#NOSLAC                        ;;
#NOSLAC                sdfiana* )
#NOSLAC                        export EPICS_BASE=/sdf/home/d/drm/src/epics/base
#NOSLAC                        if [[ -r ${EPICS_BASE}/startup/EpicsHostArch ]];
#NOSLAC                        then
#NOSLAC                                export EPICS_HOST_ARCH=$(${EPICS_BASE}/startup/EpicsHostArch)
#NOSLAC                        fi
#NOSLAC                        inspath -q "${EPICS_BASE}/bin/${EPICS_HOST_ARCH}"
#NOSLAC                        addpath -q ~/.local/bin
#NOSLAC                        umask 2
#NOSLAC                        # checkForKubernetes
#NOSLAC                        ;;
#NOSLAC                nx* )
#NOSLAC                        alias gtgray="gnome-terminal --profile='DougM Gray'"
#NOSLAC                        alias gtgrey="gnome-terminal --profile='DougM Gray'"
#NOSLAC                        alias gtblue="gnome-terminal --profile='DougM Blue'"
#NOSLAC                        alias gtbrown="gnome-terminal --profile='DougM Brown'"
#NOSLAC                        alias gtburg="gnome-terminal --profile='DougM Burgundy'"
#NOSLAC                        alias gtgreen="gnome-terminal --profile='DougM Green'"
#NOSLAC                        alias gtindigo="gnome-terminal --profile='DougM Indigo'"
#NOSLAC                        alias gtteal="gnome-terminal --profile='DougM Teal'"
#NOSLAC                        alias gt="gtgrey;gtblue;gtbrown;gtburg;gtgreen;gtindigo;gtteal"
#NOSLAC                        ;;
#NOSLAC                sdf* )
#NOSLAC                        alias gtgray="gnome-terminal --profile='DougM Gray'"
#NOSLAC                        alias gtgrey="gnome-terminal --profile='DougM Gray'"
#NOSLAC                        alias gtblue="gnome-terminal --profile='DougM Blue'"
#NOSLAC                        alias gtbrown="gnome-terminal --profile='DougM Brown'"
#NOSLAC                        alias gtburg="gnome-terminal --profile='DougM Burgundy'"
#NOSLAC                        alias gtgreen="gnome-terminal --profile='DougM Green'"
#NOSLAC                        alias gtindigo="gnome-terminal --profile='DougM Indigo'"
#NOSLAC                        alias gtteal="gnome-terminal --profile='DougM Teal'"
#NOSLAC                        alias gt="gtgrey;gtblue;gtbrown;gtburg;gtgreen;gtindigo;gtteal"
#NOSLAC                        export EPICS_BASE=/sdf/home/d/drm/src/epics/base
#NOSLAC                        export EPICS_CA_ADDR_LIST="134.79.219.255 172.26.97.63"
#NOSLAC                        export EPICS_PVA_ADDR_LIST="134.79.151.21"
#NOSLAC                        export EPICS_PVA_BROADCAST_PORT=5169
#NOSLAC                        export EPICS_PVA_AUTO_ADDR_LIST=NO
#NOSLAC                        export EPICS_PVA_SERVER_PORT=5168
#NOSLAC                        if [[ -r ${EPICS_BASE}/startup/EpicsHostArch ]];
#NOSLAC                        then
#NOSLAC                                export EPICS_HOST_ARCH=$(${EPICS_BASE}/startup/EpicsHostArch)
#NOSLAC                        fi
#NOSLAC                        inspath -q "${EPICS_BASE}/bin/${EPICS_HOST_ARCH}"
#NOSLAC                        umask 2
#NOSLAC                        # checkForKubernetes
#NOSLAC                        ;;
#NOSLAC                "lcls-dev3" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        export MATLAB_TOP=/u1/software/matlab
#NOSLAC                        export MATLAB_VERSION=R2017b
#NOSLAC                        inslib $MATLAB_TOP/$MATLAB_VERSION/bin/glnxa64
#NOSLAC                        inslib $MATLAB_TOP/$MATLAB_VERSION/sys/os/glnxa64
#NOSLAC                        export PATH=$MATLAB_TOP/$MATLAB_VERSION/bin:$PATH
#NOSLAC                        #
#NOSLAC                        # evil script sets prompt and other aliases. bad script.
#NOSLAC                        #
#NOSLAC                        _x="${PS1}"
#NOSLAC                        source /afs/slac/g/lcls/tools/script/ENVS64.bash
#NOSLAC                        PS1="${_x}"
#NOSLAC                        unset _x
#NOSLAC                        printf "The message above (%s) comes from ENVS64.bash and should be fixed.\n" "-bash: [: too many arguments"
#NOSLAC                        #DM prompt green user @ Green host sp Gray2 time Orange Gitb sp White hist sp Red Ret White .
#NOSLAC                        export PYEPICS_LIBCA=$EPICS_BASE_TOP/$EPICS_BASE_VER/lib/$EPICS_HOST_ARCH/libca.so
#NOSLAC                        export PYEPICS_LIBCOM=$EPICS_BASE_TOP/$EPICS_BASE_VER/lib/$EPICS_HOST_ARCH/libCom.so
#NOSLAC                        export EPICS_PVA_AUTO_ADDR_LIST=YES
#NOSLAC                        addca lcls-daemon0
#NOSLAC                        addca lcls-prod01:5068
#NOSLAC                        addca lcls-prod01:5063
#NOSLAC                        addca mcc-dmz
#NOSLAC                        addca 134.79.219.255
#NOSLAC                        addca 172.26.97.63
#NOSLAC                        ;;
#NOSLAC                "dev-epicsgw" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        export HTTPS_PROXY=http://sdfproxy.sdf.slac.stanford.edu:3128
#NOSLAC                        export HTTP_PROXY=$HTTPS_PROXY
#NOSLAC                        export EPICS_HOST_ARCH="rhel9-x86_64"
#NOSLAC                        export VIMRUNTIME=${XDG_CONFIG_HOME}/vim/runtime
#NOSLAC                        #
#NOSLAC                        # DANGER: (bash only)
#NOSLAC                        #         sourcing this wonderful script
#NOSLAC                        #         twice will remove PATH, making
#NOSLAC                        #         this current session unusable
#NOSLAC                        #
#NOSLAC                        # source /afs/slac/g/lcls/epics/setup/epicsenv-7.0.3.1-1.0.bash
#NOSLAC                        #
#NOSLAC                        export EPICS_PVA_AUTO_ADDR_LIST=YES
#NOSLAC                        addca lcls-daemon0
#NOSLAC                        addca lcls-prod01:5068
#NOSLAC                        addca lcls-prod01:5063
#NOSLAC                        addca mcc-dmz
#NOSLAC                        addca 134.79.219.255
#NOSLAC                        addca 172.26.97.63
#NOSLAC                        ;;
#NOSLAC                "aird-b50-srv01" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        export EPICS_HOST_ARCH="rhel7-x86_64"
#NOSLAC                        #
#NOSLAC                        # DANGER: (bash only)
#NOSLAC                        #         sourcing this wonderful script
#NOSLAC                        #         twice will remove PATH, making
#NOSLAC                        #         this current session unusable
#NOSLAC                        #
#NOSLAC                        # source /afs/slac/g/lcls/epics/setup/epicsenv-7.0.3.1-1.0.bash
#NOSLAC                        #
#NOSLAC                        export EPICS_PVA_AUTO_ADDR_LIST=YES
#NOSLAC                        export JAVA_VERS=jdk-11.0.2
#NOSLAC                        export JAVA_HOME=/afs/slac/g/lcls/package/java/$JAVA_VERS
#NOSLAC                        export MAVEN_VERS=3.6.0
#NOSLAC                        export MAVEN_HOME=/afs/slac/g/lcls/package/maven/$MAVEN_VERS
#NOSLAC                        addpath -q ${JAVA_HOME}/bin
#NOSLAC                        addpath -q ${MAVEN_HOME}/bin
#NOSLAC                        addca lcls-daemon0
#NOSLAC                        addca lcls-prod01:5068
#NOSLAC                        addca lcls-prod01:5063
#NOSLAC                        addca mcc-dmz
#NOSLAC                        addca 134.79.219.255
#NOSLAC                        addca 172.26.97.63
#NOSLAC                        addpath -q /afs/slac/g/lcls/epics/extensions/R1.1.1/bin/rhel7-x86_64
#NOSLAC                        addpath -q /afs/slac/g/lcls/epics/extensions/pvxs/R1.2.2-0.1.0/bin/rhel7-x86_64
#NOSLAC                        ;;
#NOSLAC                "mccas0" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        #
#NOSLAC                        # HDF5 tools and BSAS-NC FileWriter monitoring
#NOSLAC                        #
#NOSLAC                        addpath /afs/slac/g/lcls/package/anaconda/envs/python3_rhel7_env/bin
#NOSLAC                        addpath /afs/slac/g/lcls/package/bsasStore/current/bsasFileWriterMonitor
#NOSLAC                        export EPICS_PVA_AUTO_ADDR_LIST=YES
#NOSLAC                        addca lcls-daemon0
#NOSLAC                        addca lcls-prod01:5068
#NOSLAC                        addca lcls-prod01:5063
#NOSLAC                        addca mcc-dmz
#NOSLAC                        addca 134.79.219.255
#NOSLAC                        addca 172.26.97.63
#NOSLAC                        ;;
#NOSLAC                "lcls-daemon0" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC
#NOSLAC                        #
#NOSLAC                        # production network, uid laci; need python path for iocConsole
#NOSLAC                        #
#NOSLAC                        newlist py PYTHONPATH -e
#NOSLAC                        inspy /usr/local/lcls/epics/base/base-cpp-R4-6-0/pvaPy/lib/python/2.7/linux-x86
#NOSLAC                        inspy /usr/local/lcls/tools/python/toolbox
#NOSLAC                        inspy /usr/local/lcls/epics/base/base-cpp-R4-4-0/pvaPy/lib/linux-x86
#NOSLAC
#NOSLAC                        #
#NOSLAC                        # production network, uid laci; EPICS subnets
#NOSLAC                        #
#NOSLAC                        export EPICS_PVA_AUTO_ADDR_LIST=YES
#NOSLAC                        addca 172.27.3.255:5068
#NOSLAC                        addca mcc-dmz
#NOSLAC                        addca 172.21.40.63:5064
#NOSLAC                        addca 172.27.72.24:5070
#NOSLAC                        addca 172.27.131.255:5068
#NOSLAC                        addca 172.27.43.255:5068
#NOSLAC                        ;;
#NOSLAC                "testfac-srv01" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        export ACCTEST_ROOT=/afs/slac/g/acctest
#NOSLAC                        source /afs/slac/g/acctest/tools/script/ENVS_acctest.bash
#NOSLAC                        ;;
#NOSLAC                "testfac-camsrv01" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        export ACCTEST_ROOT=/afs/slac/g/acctest
#NOSLAC                        source /afs/slac/g/acctest/tools/script/ENVS_acctest.bash
#NOSLAC                        ;;
#NOSLAC                "testfac-camsrv02" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        export ACCTEST_ROOT=/afs/slac/g/acctest
#NOSLAC                        source /afs/slac/g/acctest/tools/script/ENVS_acctest.bash
#NOSLAC                        ;;
#NOSLAC                "testfac-asta-cs01" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        export ACCTEST_ROOT=/afs/slac/g/acctest
#NOSLAC                        source /afs/slac/g/acctest/tools/script/ENVS_acctest.bash
#NOSLAC                        ;;
#NOSLAC                "lcls-dev2" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        source /afs/slac/g/lcls/tools/script/ENVS.bash
#NOSLAC                        export JAVAVER=1.7.0_01
#NOSLAC                        source /afs/slac/g/lcls/epics/setup/go_epics_3-14-12.bash
#NOSLAC                        export JAVA_HOME=/afs/slac/g/lcls/package/java/jdk1.7.0_01
#NOSLAC                        export PATH=$JAVA_HOME/bin:$PATH
#NOSLAC                        export NETBEANS_HOME=/afs/slac/g/lcls/package/netbeans/netbeans-7.0.1
#NOSLAC                        export PATH=$NETBEANS_HOME/bin:$PATH
#NOSLAC                        export CSS_EPICS_VER=3.1.0
#NOSLAC                        export CSS_EPICS_HOME=/afs/slac/g/lcls/package/CSS/CSS_EPICS_$CSS_EPICS_VER
#NOSLAC                        export PATH=$CSS_EPICS_HOME:$PATH:/usr/afsws/bin
#NOSLAC                        export PATH=$PACKAGE_TOP/python/current/bin:$PATH
#NOSLAC                        inslib $PACKAGE_TOP/python/current/lib
#NOSLAC                        inslib $PACKAGE_TOP/python/current/lib/python2.7/lib-dynload
#NOSLAC                        ;;
#NOSLAC                "aird-pc90626" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        source /afs/slac/g/lcls/tools/script/ENVS64.bash
#NOSLAC                        source /afs/slac/g/lcls/epics/setup/epicsenv-7.0.3.1-1.0.bash
#NOSLAC                        export PACKAGE_TOP=/afs/slac/g/lcls/package
#NOSLAC                        export PATH=$PACKAGE_TOP/python/python2.7.9/linux-x86_64/bin:$PATH
#NOSLAC                        export PYEPICS_LIBCA=$EPICS_BASE_TOP/$EPICS_BASE_VER/lib/$EPICS_HOST_ARCH/libca.so
#NOSLAC                        export PYEPICS_LIBCOM=$EPICS_BASE_TOP/$EPICS_BASE_VER/lib/$EPICS_HOST_ARCH/libCom.so
#NOSLAC                        inslib $PACKAGE_TOP/python/python2.7.9/linux-x86_64/lib
#NOSLAC                        inslib $PACKAGE_TOP/python/python2.7.9/linux-x86_64/lib/python2.7/lib-dynload
#NOSLAC                        ;;
#NOSLAC                "rdsrv300" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        /usr/bin/aklog
#NOSLAC                        /usr/bin/klist
#NOSLAC                        /usr/bin/tokens
#NOSLAC                        source /afs/slac/g/lcls/epics/setup/epicsenv-7.0.3.1-1.0.bash
#NOSLAC                        ;;
#NOSLAC                "rdsrv315" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        /usr/bin/aklog
#NOSLAC                        /usr/bin/klist
#NOSLAC                        /usr/bin/tokens
#NOSLAC                        ;;
#NOSLAC                "rdsrv223" )
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        source /afs/slac/g/lcls/epics/setup/epicsenv-7.0.3.1-1.0.bash
#NOSLAC                        ;;
#NOSLAC                *)
#NOSLAC                        _CommonSLACSettings
#NOSLAC                        if [[ -r /afs/slac/g/lcls/epics/setup/epicsenv-7.0.3.1-1.0.bash ]];
#NOSLAC                        then
#NOSLAC                                source /afs/slac/g/lcls/epics/setup/epicsenv-7.0.3.1-1.0.bash
#NOSLAC                        fi
#NOSLAC                        export JAVA_HOME=/afs/slac/g/lcls/package/java/jdk1.7.0_01
#NOSLAC                        export PATH=$JAVA_HOME/bin:$PATH
#NOSLAC                        export NETBEANS_HOME=/afs/slac/g/lcls/package/netbeans/netbeans-7.0.1
#NOSLAC                        export PATH=$NETBEANS_HOME/bin:$PATH:/usr/afsws/bin
#NOSLAC                        ;;
        esac
        }
